"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

import config_setup

OPTIONS = {'argv_emulation': True}

setup(
    app=config_setup.APP,
    data_files=config_setup.DATA_FILES,
    options={'py2app': config_setup.PY2APP_OPTIONS},
    setup_requires=['py2app'],
    **config_setup.META
)
